name: Resume discord bot db service every 9:00 AM PHT, 15th and 28th of month

on:
  schedule:
    - cron: '0 1 15,28 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run resume command
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{secrets.RENDER_API_KEY}}" \
            https://api.render.com/v1/services/srv-cvpvn62dbo4c7397m8ng/resume
  
  trigger-api-build:
    runs-on: ubuntu-latest
    needs: run-script
    steps:
      - name: Trigger api endpoint to build
        run: curl -X GET https://discord-db-manager.onrender.com/health