name: Suspend discord bot consumer every 10:30 AM PHT, 15th and 28th of month

on:
  schedule:
    - cron: '30 2 15,28 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run suspend command
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{secrets.RENDER_API_KEY}}" \
            https://api.render.com/v1/services/srv-cvpvn62dbo4c7397m8ng/suspend